### ISSUE TITLE
Not working for jp

### ISSUE THREAD

**Issue by kotalol** [hawolt/Netherblade#4]
When I launch league client from Netherblade's button.
League client is Infinity loading like this.
![image](https://user-images.githubusercontent.com/126055992/220553918-7df07ae9-f584-4c04-bb36-9a3fcd7cc635.png)

**Comment by maxcutie** [comment]
is the account banned?

**Comment by hawolt** [comment]
Just figured this out now due to another report but this might be related to your name, what ingame name do you have?

**Comment by hawolt** [comment]
fixed now
