### ISSUE TITLE
App closing instantly

### ISSUE THREAD

**Issue by JustRandomAlter** [hawolt/Netherblade#7]
If you have League installed in a location that is not inside the 'Riot Games' folder, Netherblade will instantly close on start because it cannot find the system.yaml.

If Netherblade checks the RiotClientInstalls.json to find RiotClientServices.exe, it should be able to get the League Client path itself as well. 
Or there should be a manual way to choose the game location. 

As a workaround (aside from moving the whole client to 'Riot Games' folder), you can create a symlink from 'Riot Games' folder to your install location, and Netherblade will start correctly.

**Comment by hawolt** [comment]
Hello this should be working with the most recent Version, it is currently checking RiotClientInstalls.json
would appreciate if you can check this again

**Comment by JustRandomAlter** [comment]
Weirdly enough, the 1.4 version doesn't allow me to choose any region, so I can't launch the League client. But Netherblade itself starts, so that's some progress!
![image](https://github.com/Riotphobia/Netherblade/assets/29990668/0552b7cb-e5ff-4c6f-b36b-5411d324d6f4)


Here's the debug.log just in case. 
[debug.log](https://github.com/Riotphobia/Netherblade/files/11520531/debug.log)

This is probably a separate issue (should I open a new one?), as League client location doesn't change the outcome.

**Comment by hawolt** [comment]
should be resolved with 1.42
