### ISSUE TITLE
I can't Launch Client 

### ISSUE THREAD

**Issue by Charrlcode22** [hawolt/Netherblade#8]
I have java8 already, I uninstall and install my league of legends, I tried the netherblade jar and also the src code that you can run it with VS CODE, but when I click "**Launch Client**" in Netherblade it seems it won't lunch my riot client, what's the problem of this?

**Comment by hawolt** [comment]
Please try running it via IntelliJ instead of VSCode and use the most recent version, you also need to verify you are actually using Java 8 to launch Netherblade; just having it installed does not mean it is being used
